# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Redmi\Desktop\MainMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1200, 800)
        Form.setStyleSheet("background-color:rgba(16, 30, 41, 240);")

        # Главный вертикальный layout
        self.verticalLayout_main = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.verticalLayout_main.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_main.setSpacing(10)

        # КОНТЕЙНЕР ДЛЯ КНОПОК - ФИКСИРОВАННАЯ ВЫСОТА
        self.buttons_container = QtWidgets.QWidget(Form)
        self.buttons_container.setObjectName("buttons_container")
        self.buttons_container.setFixedHeight(70)  # Фиксированная высота
        self.buttons_container.setStyleSheet("""
            QPushButton {
                background-color: rgba(2, 65, 118, 255);
                color: rgba(255, 255, 255, 200);
                border-radius: 5px;
                padding: 10px;
                min-height: 30px;
                min-width: 100px;
                font-size: 12px;
                font-weight: bold;
            }
            QPushButton:hover {
                background-color: rgba(2, 65, 118, 200);
            }
            QPushButton:pressed {
                background-color: rgba(2, 65, 118, 100);
            }
        """)

        # Основной layout для контейнера кнопок - один горизонтальный layout
        self.horizontalLayout_top = QtWidgets.QHBoxLayout(self.buttons_container)
        self.horizontalLayout_top.setObjectName("horizontalLayout_top")
        self.horizontalLayout_top.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_top.setSpacing(10)

        # Все кнопки в одном горизонтальном layout
        self.pushButton = QtWidgets.QPushButton(self.buttons_container)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_top.addWidget(self.pushButton)

        self.pushButton_2 = QtWidgets.QPushButton(self.buttons_container)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_top.addWidget(self.pushButton_2)

        self.pushButton_3 = QtWidgets.QPushButton(self.buttons_container)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_top.addWidget(self.pushButton_3)

        self.pushButton_4 = QtWidgets.QPushButton(self.buttons_container)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_top.addWidget(self.pushButton_4)

        # Дополнительные кнопки
        self.adminButton = QtWidgets.QPushButton(self.buttons_container)
        self.adminButton.setMinimumSize(QtCore.QSize(0, 40))
        self.adminButton.setObjectName("adminButton")
        self.horizontalLayout_top.addWidget(self.adminButton)

        self.btnRefresh = QtWidgets.QPushButton(self.buttons_container)
        self.btnRefresh.setMinimumSize(QtCore.QSize(0, 40))
        self.btnRefresh.setObjectName("btnRefresh")
        self.horizontalLayout_top.addWidget(self.btnRefresh)

        self.btnDeleteDomain = QtWidgets.QPushButton(self.buttons_container)
        self.btnDeleteDomain.setMinimumSize(QtCore.QSize(0, 40))
        self.btnDeleteDomain.setObjectName("btnDeleteDomain")
        self.horizontalLayout_top.addWidget(self.btnDeleteDomain)

        self.btnLogout = QtWidgets.QPushButton(self.buttons_container)
        self.btnLogout.setMinimumSize(QtCore.QSize(0, 40))
        self.btnLogout.setObjectName("btnLogout")
        self.horizontalLayout_top.addWidget(self.btnLogout)

        self.btnDeleteProfile = QtWidgets.QPushButton(self.buttons_container)
        self.btnDeleteProfile.setMinimumSize(QtCore.QSize(0, 40))
        self.btnDeleteProfile.setObjectName("btnDeleteProfile")
        self.horizontalLayout_top.addWidget(self.btnDeleteProfile)

        # Растяжение чтобы кнопки не растягивались по всей ширине
        self.horizontalLayout_top.addStretch()

        # Добавляем контейнер кнопок в главный layout
        self.verticalLayout_main.addWidget(self.buttons_container)

        # Средняя часть с таблицей
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setStyleSheet("""
            QTableWidget {
                background-color: rgba(16, 30, 41, 240);
                border: 1px solid rgba(46, 82, 110, 255);
                border-radius: 5px;
                gridline-color: rgba(46, 82, 110, 150);
                color: rgb(255, 255, 255);
                font-size: 12px;
            }
            QTableWidget::item {
                background-color: rgba(25, 45, 60, 200);
                border-bottom: 1px solid rgba(46, 82, 110, 100);
                padding: 8px;
            }
            QTableWidget::item:selected {
                background-color: rgba(2, 65, 118, 200);
                color: rgb(255, 255, 255);
            }
            QTableWidget::item:hover {
                background-color: rgba(35, 55, 75, 200);
            }
            QHeaderView::section {
                background-color: rgba(2, 65, 118, 255);
                color: rgb(255, 255, 255);
                border: none;
                padding: 8px;
                font-weight: bold;
            }
            QHeaderView::section:hover {
                background-color: rgba(2, 65, 118, 200);
            }
            QHeaderView::section:pressed {
                background-color: rgba(2, 65, 118, 100);
            }
            QTableCornerButton::section {
                background-color: rgba(2, 65, 118, 255);
                border: none;
            }
            QScrollBar:vertical {
                border: none;
                background-color: rgba(16, 30, 41, 240);
                width: 12px;
                margin: 0px;
            }
            QScrollBar::handle:vertical {
                background-color: rgba(46, 82, 110, 150);
                border-radius: 6px;
                min-height: 20px;
            }
            QScrollBar::handle:vertical:hover {
                background-color: rgba(46, 82, 110, 200);
            }
            QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {
                height: 0px;
            }
            QScrollBar:horizontal {
                border: none;
                background-color: rgba(16, 30, 41, 240);
                height: 12px;
                margin: 0px;
            }
            QScrollBar::handle:horizontal {
                background-color: rgba(46, 82, 110, 150);
                border-radius: 6px;
                min-width: 20px;
            }
            QScrollBar::handle:horizontal:hover {
                background-color: rgba(46, 82, 110, 200);
            }
            QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {
                width: 0px;
            }
        """)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_main.addWidget(self.tableWidget)

        # Устанавливаем соотношения для растяжения
        self.verticalLayout_main.setStretch(0, 0)  # Контейнер кнопок - не растягивается
        self.verticalLayout_main.setStretch(1, 1)  # Таблица - растягивается

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Система мониторинга доменов"))
        self.pushButton.setText(_translate("Form", "Топ сбоев"))
        self.pushButton_2.setText(_translate("Form", "Мои домены"))
        self.pushButton_3.setText(_translate("Form", "Добавить данные"))
        self.pushButton_4.setText(_translate("Form", "Показать данные"))
        self.adminButton.setText(_translate("Form", "Админ"))
        self.btnRefresh.setText(_translate("Form", "Обновить"))
        self.btnDeleteDomain.setText(_translate("Form", "Удалить домен"))
        self.btnLogout.setText(_translate("Form", "Выйти"))
        self.btnDeleteProfile.setText(_translate("Form", "Удалить профиль"))